#geoserver-cluster
version: '3.4'

services:
  load_balance:
    image: terrabrasilis/nginx-manager:v1.0
    hostname: load_balance
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /home/queimadas/project/geoserver-cluster/nginx/conf.d:/etc/nginx/conf.d:ro
      - /srv/dados/nginx/log:/var/log/nginx

    gsmaster:
      image: terrabrasilis/geoserver-master:v1.0.6
      container_name: gsmaster
      restart: on-failure
      ports:
        - "8000:8080"
      networks:
        - proxy
      volumes: 
        - /srv/dados/geoserver/gs_datadir:/var/local/geoserver
        - /srv/dados/geoserver/gs_extensions:/var/local/geoserver-exts
      environment:
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/master
        GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/master
        CATALINA_OPTS: -XX:OnOutOfMemoryError="kill -9 %p" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1024m -Xmx3072m -Xss1024k -XX:NewSize=768m -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -DGEOSERVER_DATA_DIR=/var/local/geoserver
        instanceName: master

    gsslave1:
      image: terrabrasilis/geoserver-worker:v1.0.6
      container_name: gsslave1
      restart: on-failure
      ports:
        - "8001:8080"
      networks:
        - proxy
      volumes:
        - /srv/dados/geoserver/gs_datadir:/var/local/geoserver
        - /srv/dados/geoserver/gs_extensions:/var/local/geoserver-exts
      environment:
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/slave1
        GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/slave1
        CATALINA_OPTS: -XX:OnOutOfMemoryError="kill -9 %p" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1024m -Xmx3072m -Xss1024k -XX:NewSize=768m -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -DGEOSERVER_DATA_DIR=/var/local/geoserver
        instanceName: slave1

    gsslave2:
      image: terrabrasilis/geoserver-worker:v1.0.6
      container_name: gsslave2
      restart: on-failure
      ports:
        - "8002:8080"
      networks:
        - proxy
      volumes:
        - /srv/dados/geoserver/gs_datadir:/var/local/geoserver
        - /srv/dados/geoserver/gs_extensions:/var/local/geoserver-exts
      environment:
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/slave2
        GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/slave2
        CATALINA_OPTS: -XX:OnOutOfMemoryError="kill -9 %p" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1024m -Xmx3072m -Xss1024k -XX:NewSize=768m -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -DGEOSERVER_DATA_DIR=/var/local/geoserver
        instanceName: slave2

    gsslave3:
      image: terrabrasilis/geoserver-worker:v1.0.6
      container_name: gsslave3
      restart: on-failure
      ports:
        - "8003:8080"
      networks:
        - proxy
      volumes:
        - /srv/dados/geoserver/gs_datadir:/var/local/geoserver
        - /srv/dados/geoserver/gs_extensions:/var/local/geoserver-exts
      environment:
        COOKIE: JSESSIONID prefix
        CLUSTER_CONFIG_DIR: /var/local/geoserver/cluster/slave3
        GEOSERVER_LOG_LOCATION: /var/local/geoserver/cluster/logs/slave3
        CATALINA_OPTS: -XX:OnOutOfMemoryError="kill -9 %p" -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms1024m -Xmx3072m -Xss1024k -XX:NewSize=768m -XX:+UseParallelGC -XX:MaxGCPauseMillis=500 -DGEOSERVER_DATA_DIR=/var/local/geoserver
        instanceName: slave3

networks:
  proxy:
